public enum MenuName
{
    None,
    MainMenu,
    LoginScreen,
    RegionSelectionScreen,
    ConnectionScreen,
    CreateRoom,
    LoadingScreen,
    RoundCompleteMenu,
    ErrorWindow,
    MatchCompleteMenu,
    SettingsMenu,
    GameOverMenu,
    RoomSelection,
    InsideRoom,
    StoreSelection,
    GameDead
}